Goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Goodreads.views import landing_page, home_page

urlpatterns = [
    path("", landing_page, name="landing_page"),
    path("home/", home_page, name="home_page"),
    path("books/", include("book.urls")),
    path("users/", include("users.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/urls.py
from django.urls import path

from book.views import BookList, BookDetailView, AddReviewView, EditReviewView

app_name = "books"

urlpatterns = [
    path("", BookList.as_view(), name="list"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit-review"),
]

book/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

from users.models import CustomUser


class Book(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default="book_cover.png")

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def full_name(self):
        return f"{self.first_name} {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.book.title} was written by {self.author.first_name} {self.author.last_name}"


class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.stars_given} stars given by {self.user.username}"

book/forms.py
from django import forms

from book.models import BookReview


class BookReviewForms(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)

    class Meta:
        model = BookReview
        fields = ('stars_given', 'comment')

book/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView

from book.forms import BookReviewForms
from book.models import Book, BookReview


# class BookList(ListView):
#     template_name = "books/list.html"
#     queryset = Book.objects.all()
#     context_object_name = "books"

class BookList(View):
    def get(self, request):
        books = Book.objects.all().order_by("id")

        search_query = request.GET.get('q', '')
        if search_query:
            books = books.filter(title__icontains=search_query)

        paginator = Paginator(books, 4)
        page_num = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_num)

        context = {"page_obj": page_obj, "q": search_query}
        return render(request, "books/list.html", context)


class BookDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)

        review_form = BookReviewForms()
        context = {"book": book, 'review_form': review_form}
        return render(request, "books/detail.html", context)


class AddReviewView(View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForms(data=request.POST)

        if review_form.is_valid():
            BookReview.objects.create(
                book=book,
                user=request.user,
                stars_given=review_form.cleaned_data['stars_given'],
                comment=review_form.cleaned_data['comment']
            )
            return redirect(reverse("books:detail", kwargs={'id':book.id}))

        context = {"book": book, 'review_form': review_form}
        return render(request, "books/detail.html", context)


class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        return render(request, 'books/edit_review.html')

book/templates/books/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Book detail page{% endblock %}

{% block content %}
    <div class="row mb-4">
        <div class="col-2">
            <img class="cover-pic" src="{{ book.cover_picture.url }}" alt="cover pic">
        </div>

        <div class="col-6 ms-3">
            <h3>{{ book.title }}</h3>
            <span class="fst-italic">
                Authored by
                {% for book_author in book.bookauthor_set.all %}
                    {% if forloop.last %}
                        {{book_author.author.full_name}}
                    {% else %}
                        {{book_author.author.full_name}},
                    {% endif %}
                {% endfor %}
            </span>
            <p>{{ book.description }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <form method="post" action="{% url 'books:reviews' book.id %}">
                {% csrf_token %}
                {{review_form | crispy}}
                <button class="btn btn-success">Add review</button>
            </form>
        </div>
    </div>


    {% if book.bookreview_set.exists %}
        <h4>Reviews</h4><hr>

            {% for review in book.bookreview_set.all %}
                <div class="row mb-3">
                    <div class="col-2">
                        <img class="small-profile-pic" src="{{review.user.profile_picture.url}}" alt="">
                    </div>
                    <div class="col-7">
                        <b>{{review.user.username}}</b> rated it {{review.stars_given}} stars <span class="fw-lighter">{{review.created_at}}</span>
                        {% if request.user == review.user %}
                            <a href="{% url 'books:edit-review' book.id review.id %}"><i class="bi bi-pen"></i></a>
                            <a href="#"><i class="bi bi-trash"></i></a>
                        {% endif %}
                        
                        <p class="font-monospace">{{review.comment}}</p>
                    </div>
                </div>

            {% endfor %}
    {% endif %}


{% endblock %}

book/templates/books/edit_review.html
{% extends 'base.html' %}

{% block title %}Edit review{% endblock %}

{% block content %}
    <h3>Review edit</h3>
{% endblock %}

book/templates/books/list.html
{% extends 'base.html' %}

{% block title %} Book list page {% endblock %}
{% block content %}

<h3>Books</h3>

    <div class="row mb-3">
        <div class="col-4">
            <form method="get" class="d-flex">
                <input name="q" type="text" value="{{q}}" class="form-control me-2" placeholder="search">
                <button class="btn btn-success">Search</button>
            </form>
        </div>
    </div>

{% if page_obj %}
    <ul>
        {% for book in page_obj.object_list %}
            <div class="row mb-4">
                <div class="col-2">
                    <img class="cover-pic" src="{{book.cover_picture.url}}" alt="cover pic">
                </div>
                <div class="col-6 ms-4">
                    <a href="{% url 'books:detail' book.id %}">{{ book.title }}</a>

                    <p>
                        {{book.description|slice:":300"}}...
                    </p>
                </div>
            </div>
        {% endfor %}


            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo;first</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">previous</a></li>
                {% endif %}

                <li class="page-item active">
                    <a href="#" class="page-link">{{ page_obj.number }}</a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.paginator.num_pages}}">last&raquo;</a></li>
                {% endif %}
            </ul>
    </ul>

{% else %}
    No found book.
{% endif %}

{% endblock %}