Goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Goodreads.views import landing_page, home_page

urlpatterns = [
    path("", landing_page, name="landing_page"),
    path("home/", home_page, name="home_page"),
    path("books/", include("book.urls")),
    path("users/", include("users.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/urls.py
from django.urls import path

from book.views import BookList, BookDetailView, AddReviewView, EditReviewView

app_name = "books"

urlpatterns = [
    path("", BookList.as_view(), name="list"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit-review"),
]

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = "users"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit", ProfileUpdateView.as_view(), name="profile-edit"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="default_profile_pic.jpg")

users/forms.py
from django import forms
from django.core.mail import send_mail

from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ("username", "first_name", "last_name", "email", "password")

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', "profile_picture")

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from users.forms import UserCreateForm, UserUpdateForm


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {"form": create_form}
        return render(request, "users/register.html", context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)
        if create_form.is_valid():
            create_form.save()
            return redirect("landing_page")
        else:
            context = {
                "form": create_form
            }
            return render(request, "users/register.html", context)


class LoginView(View):
    def get(self, request):
        user_login = AuthenticationForm()
        context = {
            "user_login": user_login
        }
        return render(request, "users/login.html", context)

    def post(self, request):
        user_login = AuthenticationForm(data=request.POST)
        if user_login.is_valid():
            user = user_login.get_user()
            login(request, user)
            messages.success(request, "You have successfully logged in.")
            return redirect("books:list")
        else:
            context = {"user_login": user_login}
            return render(request, "users/login.html", context)


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        # if not request.CustomUser.is_authenticated:   LoginRequiredMixin
        #    return redirect("CustomUsers:login")      LoginRequiredMixin
        context = {"user": request.user}
        return render(request, 'users/profile.html', context)


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out!")
        return redirect("landing_page")


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_form = UserUpdateForm(instance=request.user)
        context = {"form": user_form}
        return render(request, "users/profile_edit.html", context)

    def post(self, request):
        user_form = UserUpdateForm(instance=request.user, data=request.POST, files=request.FILES)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, "You have successfully updated your profile.")
            return redirect("users:profile")

        return redirect(request, "users/profile_edit.html", {"form": user_form})

users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Login Page{% endblock title%}

{% block content %}
    <h3>Login</h3>
    <div class="row">
        <div class="col-4">
                <form method="post">
                {% csrf_token %}
                {{ user_login | crispy }}
                <button class="btn btn-primary" type="submit">LogIn</button>
                <span class="ms-3">If you don't have account <a href="{% url 'users:register' %}">register</a></span>
        </form>
        </div>
    </div>


{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}

    {% block title %}Profile Page{% endblock title%}

{% block content %}

<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
    <div class="card p-4">
        <div class=" image d-flex flex-column justify-content-center align-items-center">
            <button class="btn btn-secondary">
                <img class="profile-pic" src="{{ user.profile_picture.url }}" alt="Profile pic">
            </button>
            <span class="name mt-3">{{user.first_name}}</span>
            <span class="idd">@{{user.username}}</span>
            <span class="idd">{{user.email}}</span>

            <div class=" d-flex mt-2">
               <a class="btn btn-dark" href="{% url 'users:profile-edit' %}">edit profile</a>
            </div>


            <span class="join">{{user.date_joined |date:"M d, Y"}}</span>
            {% if user.is_active %}
            <span>status : active</span>
            {% else %}
            <span>status : not active</span>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/profile_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h3>Profile Update</h3>

    <div class="row">
        <div class="col-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-primary" type="submit">Save changes</button>
            </form>
        </div>
    </div>


{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Register page {% endblock %}

{% block content %}
<h3>Register</h3>
    <div class="row">
        <div class="col-4">
            <form method="post" action="{% url 'users:register' %}">
                {% csrf_token %}
                {{form | crispy}}
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>


{% endblock %}