Goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Goodreads.views import landing_page, home_page

urlpatterns = [
    path("", landing_page, name="landing_page"),
    path("home/", home_page, name="home_page"),
    path("books/", include("book.urls")),
    path("users/", include("users.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/urls.py
from django.urls import path

from book.views import BookList, BookDetailView, AddReviewView, EditReviewView

app_name = "books"

urlpatterns = [
    path("", BookList.as_view(), name="list"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit-review"),
]

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = "users"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit", ProfileUpdateView.as_view(), name="profile-edit"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Goodreads {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body class="m-5">

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home_page' %}">Home</a>
        </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'books:list' %}">Books</a>
        </li>
      </ul>

        <div class="me-5">
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{request.user.username}}
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                      </ul>
                    </li>
                </ul>
            {% else %}
                <a class="btn btn-danger" href="{% url 'users:login' %}">Login</a>
            {% endif %}
        </div>

    </div>
  </div>
</nav>

<div class="container">
    <div class="mt-4">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}}" role="alert">
                    {{ message}}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    {% block content %} {% endblock %}
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<h3>All reviews</h3>

    {% for review in page_obj %}
            <div class="container posts-content">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="card mb-4">
                          <div class="card-body">
                            <div class="media mb-3">
                              <img src="{{review.user.profile_picture.url}}" class="d-block ui-w-40 rounded-circle" alt="">
                              <div class="media-body ml-3">
                                  <b>{{review.user.username}}</b> rated this book {{review.stars_given}} stars
                                <div class="text-muted small">{{review.created_at | date:"d M, Y"}}</div>
                              </div>
                            </div>

                            <p>
                              {{review.comment | truncatechars:300}}
                            </p>
                              <div>
                                  <img class="cover-pic center" src="{{review.book.cover_picture.url}}" alt="">
                              </div>
                          </div>

                        </div>
                    </div>

                </div>
            </div>
    {% endfor %}
    <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo;first</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">previous</a></li>
                {% endif %}

                <li class="page-item active">
                    <a href="#" class="page-link">{{ page_obj.number }}</a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.paginator.num_pages}}">last&raquo;</a></li>
                {% endif %}
    </ul>

{% endblock %}

templates/landing_page.html
{% extends 'base.html' %}

{% block content %}
<h1>Landing Page</h1>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been
    the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley
    of type and scrambled it to make a type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised
    in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently
    with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
</p>

{% endblock %}